/**
 * Shared types for SHREDR services
 */

// ============ STORAGE TYPES ============

export interface NonceState {
    currentNonce: string;  // Base64 encoded current nonce
    currentIndex: number;
    walletPubkeyHash: string;
}

// ============ NONCE TYPES ============

export interface GeneratedNonce {
    nonce: Uint8Array;
    index: number;
    walletPubkeyHash: string;
}

export interface EncryptedNoncePayload {
    encryptedBlob: string;  // Base64 encoded IV + ciphertext
    version: number;
}

export interface DerivedKeys {
    masterSeed: Uint8Array;
    encryptionKey: CryptoKey;
}

// ============ ENCRYPTION TYPES ============

export interface EncryptedNonce {
    id: string;
    ciphertext: string;      // Base64 encoded encrypted data
    iv: string;              // Base64 encoded initialization vector
    salt: string;            // Base64 encoded salt for key derivation
    createdAt: number;
    consumed: boolean;       // True if nonce has been used (one-time use)
    consumedAt?: number;     // Timestamp when consumed
}

export interface DecryptedNonce {
    nonce: Uint8Array;
    index: number;           // Burner index for HD derivation
    timestamp: number;
}

export interface BurnerKeyPair {
    publicKey: Uint8Array;
    secretKey: Uint8Array;
    address: string;
    nonce: Uint8Array;
    nonceIndex: number;
}

export interface EncryptionKeyMaterial {
    key: CryptoKey;
    salt: Uint8Array;
}

export interface RecoveryResult {
    success: boolean;
    burners: BurnerKeyPair[];
    failedAttempts: number;
}

export interface ConsumeNonceResult {
    success: boolean;
    nonceId: string;
    consumedAt: number;
    error?: string;
}

export interface LocalNonceData {
    nonce: string;           // Base64 encoded nonce
    index: number;
    createdAt: number;
    burnerPublicKey: string; // For reference
}

export interface NonceDestructionProof {
    nonceId: string;
    destructionSignature: string;  // Signed by wallet to prove ownership
    timestamp: number;
}

// ============ API TYPES (Backend Communication) ============

/**
 * Encrypted blob stored on backend
 * Backend cannot decrypt - only stores opaque data
 */
export interface NonceBlob {
    id: string;                  // Unique blob ID (generated by backend)
    encryptedBlob: string;       // Base64 encoded IV + ciphertext
    createdAt: number;           // Timestamp
}

/**
 * Request to create a new blob
 */
export interface CreateBlobRequest {
    encryptedBlob: string;  // Base64 encoded IV + ciphertext
}

/**
 * Result of trying to decrypt blobs
 */
export interface DecryptBlobsResult {
    found: boolean;              // Did we find a matching blob?
    blob?: NonceBlob;            // The matching blob (if found)
    decryptedNonce?: GeneratedNonce;  // Decrypted nonce data
}

/**
 * Result of consuming a nonce
 */
export interface ConsumeResult {
    consumedNonce: GeneratedNonce;    // The nonce that was consumed (DELETE from backend)
    consumedBlobId: string;           // Blob ID to delete
    newNonce: GeneratedNonce;         // New nonce (UPLOAD to backend)
    newBlobData: CreateBlobRequest;   // Encrypted blob to upload
}

/**
 * API client interface - what the frontend expects from backend
 */
export interface NonceBlobAPI {
    // Fetch all blobs (user tries to decrypt each to find theirs)
    fetchAllBlobs(): Promise<NonceBlob[]>;
    
    // Create a new blob
    createBlob(data: CreateBlobRequest): Promise<NonceBlob>;
    
    // Delete a blob by ID
    deleteBlob(id: string): Promise<boolean>;
}

// ============ WEBSOCKET TYPES ============

export interface WebSocketTransactionMessage {
    type: 'transaction';
    data: any;  // Transaction data from Helius
    timestamp: string;  // ISO 8601 timestamp
}

export interface WebSocketStatusMessage {
    type: 'status';
    clients_count: number;
    timestamp: string;  // ISO 8601 timestamp
}

export interface WebSocketAccountUpdateMessage {
    type: 'accountUpdate';
    lamports: number;
    account: number;  // slot or some identifier
}

export type WebSocketMessage = WebSocketTransactionMessage | WebSocketStatusMessage | WebSocketAccountUpdateMessage;

// ============ ERROR TYPES ============

export class DecryptionError extends Error {
    readonly reason: 'wrong_key' | 'corrupted' | 'unknown';

    constructor(reason: 'wrong_key' | 'corrupted' | 'unknown', message: string) {
        super(message);
        this.name = 'DecryptionError';
        this.reason = reason;
    }
}
